stages:
  - verify
  - test
  - build
  - deploy

verify:
  stage: verify
  image: gradle:8-jdk21
  script:
    - gradle checkstyleMain checkstyleTest
  only:
    - master

test:
  stage: test
  image: gradle:8-jdk21
  script:
    - gradle test
  only:
    - master

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t frontend-angular ./frontend
    - docker build -t backend-spring ./backend
  only:
    - master