stages:
  - verify
  - test
  - build
  - deploy

verify-frontend:
  stage: verify
  image: node:20
  script:
    - cd ./angular/
    - npm install
    - npm run lint || true

verify-backend:
  stage: verify
  image: maven:3.9.9-amazoncorretto
  script:
    - cd ./spring/
    - mvn checkstyle:check || true

test-backend:
  stage: test
  image: maven:3.9.9-amazoncorretto
  script:
    - cd ./spring/
    - mvn test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t frontend-angular ./frontend
    - docker build -t backend-spring ./backend
  only:
    - master

